[package]
name = "mb_goban"
description = "A go board data type"
license = "MIT"
repository = "https://github.com/ottobrown/mbaduk/tree/main/goban"
readme = "../README.md"
version = "0.1.0"
edition = "2021"

[dependencies]
fxhash = "0.2.1"
